baseURL = 'https://www.erikxu.me/'
locale = 'en-us'
title = 'Notes & Thoughts'
theme = 'risotto'

[menu]
  [[menu.main]]
    name = 'Notes'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'Reading'
    url = '/reading/'
    weight = 2
