baseURL = 'https://www.erikxu.me/'
locale = 'en-us'
title = 'Notes & Thoughts'
theme = 'risotto'

[params.analytics]
  cloudflareToken = 'bf47fd86a34e4334856687ecf78add45'

[menu]
  [[menu.main]]
    name = 'Notes'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'Reading'
    url = '/reading/'
    weight = 2
